name: Publish Release on Push to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # Adjust if you have a custom build script

    - name: Create a GitHub release
      uses: gh-actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ github.run_number }}"
        release_name: "Release v${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Publish the package (optional)
      run: npm publish  # Optional, only if you're publishing the package to npm
